import { z } from 'zod';

// Represents the secret password to insert generated by the backend
export const secretSchema = z.object(
    {
        value: z.string().length(20)
    }
)
export type SecretRecord = z.infer<typeof secretSchema>;

//Represent a memory 
//NOTE: this is the basic minimum memory, later other elements may be added
export const memorySchema = z.object({
    id: z.string().uuid(),
    heading: z.string().max(100).nullable(),
    text: z.string().max(100).nullable(),
    mediaId: z.string().nullable() //Same as in mediaRecordSchema
})
export type MemoryRecord = z.infer<typeof memorySchema>;

//Media metadata
export const mediaRecordSchema = z.object({
  id: z.string(), 
  filename: z.string(),
  width: z.number().int().positive().optional(),
  height: z.number().int().positive().optional()
});
export type MediaRecord = z.infer<typeof mediaRecordSchema>;

export const MAX_MEMORIES_COUNT = 50;

//Complete database schema
export const dbSchema = z.object({
  secret: secretSchema,
  config: z.object({
    anniversaryDate: z.string().date().or(z.literal('')),
    sealMediaId: z.string().nullable().optional()
  }),
  memories: z.array(memorySchema).max(MAX_MEMORIES_COUNT, "Cannot exceed 50 memories"),
  media: z.array(mediaRecordSchema).max(50, "Cannot exceed 50 media files")
});
export type DatabaseSchema = z.infer<typeof dbSchema>;

// Initial database template without secret
export const initialDb: Omit<DatabaseSchema, "secret"> = {
  config: { anniversaryDate: "", sealMediaId: null },
  memories: [],
  media: [],
};

// Factory function to construct a fresh, validated database record
export function createDefaultDb(secret: SecretRecord): DatabaseSchema {
  return dbSchema.parse({
    secret,
    ...initialDb,
  });
}

