import { z } from 'zod';

// Represents the secret password to insert generated by the backend
export const secretSchema = z.object(
    {
        value: z.string().length(20)
    }
)
//Represent a memory 
//NOTE: this is the basic minimum memory, later other elements may be added
export const memorySchema = z.object({
    id: z.string().uuid(),
    heading: z.string().max(100).nullable(),
    text: z.string().max(100).nullable(),
    mediaId: z.string().nullable() //Same as in mediaRecordSchema
})
export type MemoryRecord = z.infer<typeof memorySchema>;

//Media metadata
export const mediaRecordSchema = z.object({
  id: z.string(), 
  filename: z.string(),
  width: z.number().int().positive().optional(),
  height: z.number().int().positive().optional()
});
export type MediaRecord = z.infer<typeof mediaRecordSchema>;

//Complete database schema
export const dbSchema = z.object({
  config: z.object({
    anniversaryDate: z.string().date()
  }),
  memories: z.array(memorySchema),
  media: z.array(mediaRecordSchema).max(20, "Cannot exceed 20 media files")
});
export type DatabaseSchema = z.infer<typeof dbSchema>;

